/* eslint-disable */
// GENERATED by packages/schema/scripts/gen.mjs — do not edit.

/**
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "ObservationKind".
 */
export type ObservationKind =
  | "advance"
  | "withdrawal"
  | "seizure"
  | "infiltration"
  | "assault"
  | "counterattack"
  | "strike"
  | "unit_presence"
  | "other";
/**
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "Actor".
 */
export type Actor = "RU" | "UA" | "unknown";
/**
 * Epistemic status of a single observation — drives line/marker style.
 *
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "Status".
 */
export type Status = "assessed" | "geolocated" | "claimed" | "reported" | "denied";
export interface DayBundle {
  day: number;
  date: string;
  /**
   * layer id -> FeatureCollection; areas, lines and diff polygons
   */
  layers: {
    [k: string]: FeatureCollection;
  };
  observations: Observation[];
}
/**
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "FeatureCollection".
 */
export interface FeatureCollection {
  type: "FeatureCollection";
  features: Feature[];
}
/**
 * Loose GeoJSON Feature (geometry left untyped to keep the TS side simple).
 *
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "Feature".
 */
export interface Feature {
  type: "Feature";
  id: string | number | null;
  geometry: {
    [k: string]: unknown;
  };
  properties: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "Observation".
 */
export interface Observation {
  /**
   * sha1 of (source_id, document_id, ordinal)
   */
  id: string;
  day: number;
  date: string;
  source_id: string;
  kind: ObservationKind;
  actor: Actor;
  status: Status;
  place: PlaceRef;
  /**
   * Resolved anchor point
   */
  geometry: PointGeometry | null;
  /**
   * Nearest point on that day's front line (for callout leader lines)
   */
  front_anchor: PointGeometry | null;
  /**
   * Operational direction, e.g. 'Pokrovsk direction'
   */
  axis: string | null;
  units: string[];
  /**
   * Our own paraphrase, English
   */
  summary: string;
  citations: Citation[];
  /**
   * Admiralty information credibility 1..6
   */
  credibility: number;
  /**
   * Fusion cluster (same place/day/kind)
   */
  cluster_id: string | null;
  /**
   * Independent sources in the cluster
   */
  corroboration: number;
  /**
   * Claim lies outside the assessed-control area for the day
   */
  conflicts_with_assessment: boolean;
}
/**
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "PlaceRef".
 */
export interface PlaceRef {
  /**
   * Name as written in the source
   */
  name: string;
  /**
   * e.g. 'geonames:704508'
   */
  gazetteer_id: string | null;
  /**
   * ISW-style transliteration
   */
  canonical_name: string | null;
  /**
   * in | near | north_of | ... | between
   */
  relation: string;
  distance_km: number | null;
  resolution_confidence: number;
}
/**
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "PointGeometry".
 */
export interface PointGeometry {
  type: "Point";
  coordinates: number[];
}
/**
 * This interface was referenced by `DayBundle`'s JSON-Schema
 * via the `definition` "Citation".
 */
export interface Citation {
  source_id: string;
  url: string;
  published_at: string | null;
  /**
   * <=25 words verbatim; never republish full text
   */
  excerpt: string | null;
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "SourceKind".
 */
export type SourceKind = "analytic" | "osint_map" | "milblog" | "official" | "telegram" | "news";
/**
 * Which side the source is aligned with (unknown = neutral)
 */
/**
 * NATO/Admiralty source-reliability grade (AJP-2.1). Assigned per *source*.
 *
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "Reliability".
 */
export type Reliability = "A" | "B" | "C" | "D" | "E" | "F";
export type LayerFormat = "bundle" | "temporal_pmtiles";
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "Actor".
 */
export type Actor1 = "RU" | "UA" | "unknown";
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "LayerFormat".
 */
export type LayerFormat1 = "bundle" | "temporal_pmtiles";
export interface Manifest {
  version: 1;
  epoch: string;
  generated_at: string;
  /**
   * True for demo fixtures; UI shows a banner
   */
  synthetic: boolean;
  day_min: number;
  day_max: number;
  sources: Source[];
  layers: LayerDescriptor[];
  /**
   * One entry per day in [day_min, day_max]
   */
  stats: DayStat[];
  bundle_url_template: string;
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "Source".
 */
export interface Source {
  /**
   * Stable slug, e.g. 'isw', 'deepstate', 'tg:rybar'
   */
  id: string;
  name: string;
  kind: SourceKind;
  side: Actor;
  reliability: Reliability;
  url: string;
  language: string;
  /**
   * Terms the data is used under; shown in attribution
   */
  license_note: string;
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "LayerDescriptor".
 */
export interface LayerDescriptor {
  /**
   * e.g. 'isw.assessed_control', 'deepstate.front'
   */
  id: string;
  source_id: string;
  geom: "area" | "line" | "point";
  /**
   * ControlCategory / LineKind / 'observations'
   */
  category: string;
  format: LayerFormat;
  /**
   * For temporal_pmtiles: archive URL
   */
  url: string | null;
  source_layer: string | null;
  /**
   * Inclusive [from, to] day ranges with data
   */
  day_ranges: [unknown, unknown][];
}
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "DayStat".
 */
export interface DayStat {
  day: number;
  ru_gain_km2: number;
  ua_gain_km2: number;
  observations: number;
  claims: number;
}
