// JSON Schema (exported by `milmap schema` from pipeline/milmap/models.py) -> TS types.
// Never edit src/generated.ts by hand: change the Pydantic model and run `pnpm schema:gen`.
import { compileFromFile } from "json-schema-to-typescript";
import { readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "schema");
let out = "/* eslint-disable */\n// GENERATED by packages/schema/scripts/gen.mjs — do not edit.\n\n";
const seen = new Set();
for (const file of readdirSync(dir).filter((f) => f.endsWith(".schema.json")).sort()) {
  const ts = await compileFromFile(join(dir, file), {
    bannerComment: "",
    additionalProperties: false,
    unreachableDefinitions: true,
    style: { semi: true, singleQuote: false },
  });
  // Both schemas share $defs; keep the first declaration of each exported name.
  const blocks = ts.split(/\n(?=\/\*\*|export )/);
  for (const block of blocks) {
    const m = block.match(/export (?:interface|type) (\w+)/);
    if (m && seen.has(m[1])) continue;
    if (m) seen.add(m[1]);
    out += block.trimEnd() + "\n";
  }
}
writeFileSync(join(root, "src", "generated.ts"), out);
console.log("wrote src/generated.ts:", [...seen].join(", "));
